### ISSUE TITLE
Link to the new contributing site

### ISSUE THREAD

**Issue by seisman** [seismo-learn/website#29]
Need to add a link to the new contributing site https://seismo-learn.org/contributing/.

Where to add the link?

**Comment by core-man** [comment]
> Need to add a link to the new contributing site https://seismo-learn.org/contributing/.
> 
> Where to add the link?

Replace "欢迎地震学科研工作者通过 Issues 和  GitHub Discussions 给予反馈。" with new text and link? Right now Issues ans Discussions link to website repo.
